import Head from 'next/head'
import { useEffect } from 'react'

import Error404 from '../src/features/404/Error404'

import { useAppSelector } from '../src/app/hooks'
import { selectDarkModeInit, selectDarkModeState } from '../src/features/darkmode/darkModeSlice' 



const Error404Page = () => {
  const darkmode = useAppSelector( selectDarkModeState )
  const darkmodeInit = useAppSelector( selectDarkModeInit )

  useEffect( () => { 
    if (darkmodeInit) {
      if (darkmode) {
        document.querySelector( 'body' )?.classList.remove( 'bodyFromDark' ) 
        document.querySelector( 'body' )?.classList.add( 'bodyToDark' ) 
      } else {
        document.querySelector( 'body' )?.classList.remove( 'bodyToDark' ) 
        document.querySelector( 'body' )?.classList.add( 'bodyFromDark' ) 
      }
    }
  }, [darkmode, darkmodeInit])

  return (
    <>
      <Head>
        <title>404 Not Found</title>
        <meta name="description" content="Generated by create nex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Error404/>
      </main>
    </>
  )
}

export default Error404Page
