import Head from 'next/head'

import Base from '../src/features/base/Base'

export default function Home() {
  return (
    <>
      <Head>
        <title>Michael Vaden</title>
        <meta name="description" content="Generated by create nex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Base/>
      </main>
    </>
  )
}
