# Generated by Django 4.1.5 on 2023-01-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_tpye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tpye',
            new_name='type',
        ),
    ]
