# Generated by Django 4.1.5 on 2023-01-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tpye_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
