import Head from 'next/head'
import { useEffect } from 'react'

import Base from '../../src/features/base/Base'
import Blog from '../../src/features/blog/Blog'

import { useAppSelector } from '../../src/app/hooks'
import { selectDarkModeInit, selectDarkModeState } from '../../src/features/darkmode/darkModeSlice' 


const WorksPage = () => {
  // darkmode
  const darkmode = useAppSelector( selectDarkModeState )
  const darkmodeInit = useAppSelector( selectDarkModeInit )

  useEffect( () => { 
    if (darkmodeInit) {
      if (darkmode) {
        document.querySelector( 'body' )?.classList.remove( 'bodyFromDark' ) 
        document.querySelector( 'body' )?.classList.add( 'bodyToDark' ) 
      } else {
        document.querySelector( 'body' )?.classList.remove( 'bodyToDark' ) 
        document.querySelector( 'body' )?.classList.add( 'bodyFromDark' ) 
      }
    }
  }, [darkmode, darkmodeInit])

  return (
    <>
      <Head>
        <title>Michael Vaden</title>
        <meta name="description" content="Generated by create nex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Base/>
        <Blog type='works' id={3}/>
      </main>
    </>
  )
}

export default WorksPage